// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Greeting$ReasonRandomColor from "./Greeting.bs.js";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Greeting$ReasonRandomColor.make, {
            name: "John"
          }), root);
}

export {
  
}
/* root Not a pure module */
